name: ecosport_launcher
description: EcoSport Launcher

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  weather: ^2.0.1
  weather_icons: ^3.0.0
  retry: ^3.1.0
  fpdart: ^0.3.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_bloc: ^8.1.1
  package_info_plus: ^3.0.2
  device_apps: ^2.2.0
  flutter_spinkit: ^5.1.0
  animate_do: ^3.0.2
  hydrated_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

